[tool.poetry]
name = "numpoly"
version = "0.0.6"
authors = ["Jonathan Feinberg <jonathf@gmail.com>"]
repository = "https://github.com/jonathf/numpoly"
description = "Polynomials as a numpy datatype"
readme = "README.rst"
classifiers = [
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Mathematics",
        "License :: OSI Approved :: BSD License",
        "Natural Language :: English",
]

[tool.poetry.dependencies]
python = ">=3.5||2.7.16"
numpy = "*"

[tool.poetry.dev-dependencies]
sympy = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
codecov = "*"
coverage = "*"
