[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "numpoly"
version = "1.0.7"
description = "Polynomials as a numpy datatype"
license = "BSD-2-Clause"
authors = ["Jonathan Feinberg"]
repository = "https://github.com/jonathf/numpoly"
documentation = "https://numpoly.readthedocs.io"
readme = "README.rst"
classifiers = [
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Mathematics",
        "License :: OSI Approved :: BSD License",
        "Natural Language :: English",
]

[tool.poetry.dependencies]
python = "*"
numpy = "^1.16"
six = "*"

[tool.poetry.dev-dependencies]
sympy = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
codecov = "*"
coverage = "*"
Sphinx = "*"
pydocstyle = "3.0.0"
sphinx_automodapi = "*"
