[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "numpoly"
version = "0.1.7"
authors = ["Jonathan Feinberg <jonathf@gmail.com>"]
repository = "https://github.com/jonathf/numpoly"
description = "Polynomials as a numpy datatype"
readme = "README.rst"
classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Mathematics",
        "License :: OSI Approved :: BSD License",
        "Natural Language :: English",
]

[tool.poetry.dependencies]
numpy = "^1.16"

[tool.poetry.dev-dependencies]
sympy = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
codecov = "*"
coverage = "*"
Sphinx = "*"
pydocstyle = "3.0.0"
sphinx_automodapi = "*"
